spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: password
      database: piggymetrics-auth-service
      port: 27017
server:
  servlet:
    context-path: /uaa
  port: 5000
